repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-json
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        args: ["-q","-r","."]
  - repo: https://github.com/pypa/pip-audit
    rev: v2.7.3
    hooks:
      - id: pip-audit
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.11.0
    hooks:
      - id: helm-docs
        args: ["--chart-search-root=charts"]
  - repo: local
    hooks:
      - id: helm-lint
        name: helm lint
        entry: bash -lc 'command -v helm >/dev/null 2>&1 && helm lint charts/openworld-specialty-chemicals || echo "helm not installed; skipping helm lint"'
        language: system
        files: ^charts/openworld-specialty-chemicals/
