version: '3.8'
services:
  app:
    build: .
    image: openworld-specialty-chemicals:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: ["openworld-chem", "dashboard", "--host", "0.0.0.0", "--port", "8000"]
