site_name: OpenWorld Specialty Chemicals
theme:
  name: material
nav:
  - Home: index.md
  - User Guide: user-guide.md
  - Developer Guide: developer-guide.md
  - CLI: cli.md
  - Data Requirements: data_requirements.md
  - Chart Repo: chart_repo.md
  - Operations: operations.md
  - Architecture: ../ARCHITECTURE.md
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
