site_name: OpenWorld Specialty Chemicals
repo_url: https://github.com/<org>/OpenWorld-SpecialtyChemicals
theme:
  name: material
nav:
  - Home: index.md
  - User Guide: user-guide.md
  - Developer Guide: developer-guide.md
  - Architecture: ../ARCHITECTURE.md
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite

