apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openworld-specialty-chemicals.fullname" . }}
type: Opaque
data:
  {{- if .Values.secrets.apiToken }}
  api-token: {{ .Values.secrets.apiToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.metricsToken }}
  metrics-token: {{ .Values.secrets.metricsToken | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.redisUrl }}
  redis-url: {{ .Values.secrets.redisUrl | b64enc | quote }}
  {{- end }}
