apiVersion: v1
entries:
  openworld-specialty-chemicals:
  - apiVersion: v2
    appVersion: 0.2.1
    created: "2025-09-08T02:54:37.218619411Z"
    description: Monitoring platform dashboard and CLI server
    digest: d2062b06f337d948a579ae563672a6b41f825e4470a983b42cb636cff6d5f3a1
    name: openworld-specialty-chemicals
    type: application
    urls:
    - https://llamasearchai.github.io/OpenWorld-SpecialtyChemicals/charts/openworld-specialty-chemicals-0.1.0.tgz
    version: 0.1.0
generated: "2025-09-08T02:54:37.218172501Z"
