image:
  repository: your-dockerhub-user/openworld-specialty-chemicals
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  className: ""
  hosts:
    - host: example.com
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

env:
  LOG_FORMAT: text
  OW_SC_RL_PER_SEC: "10"
  OW_SC_WS_MSGS_PER_SEC: "20"
  OW_SC_WS_MAX_MESSAGE_BYTES: "8192"
  OW_SC_MAX_CSV_BYTES: "10485760"
  OW_SC_MAX_CSV_ROWS: "1000000"
  OW_SC_CORS_ORIGINS: "*"

secrets:
  apiToken: ""
  metricsProtect: false
  metricsToken: ""
  redisUrl: ""
  redisChannel: "owsc:effluent"

replicaCount: 1

autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
