name: Chart Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  publish-chart:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Package chart
        run: |
          mkdir -p dist-charts
          helm lint charts/openworld-specialty-chemicals
          helm package charts/openworld-specialty-chemicals -d dist-charts

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Publish chart to gh-pages
        run: |
          set -euo pipefail
          mkdir -p gh-pages/charts
          cp dist-charts/*.tgz gh-pages/charts/
          cd gh-pages
          helm repo index charts --url https://$GITHUB_REPOSITORY_OWNER.github.io/${GITHUB_REPOSITORY#*/}/charts
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add charts
          git commit -m "chore(charts): publish package for ${GITHUB_REF_NAME}"
          git push
