name: ci
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10","3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        run: pip install uv
      - name: Install deps
        run: uv pip install -e ".[dev]" --system
      - name: Run tests
        run: pytest -q --cov=openworld_specialty_chemicals --cov-report=term-missing
      - name: Ruff lint
        run: uv pip install ruff && ruff check .

name: ci

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        run: python -m pip install --upgrade pip && pip install uv
      - name: Install dependencies (editable, dev extras)
        run: uv pip install -e ".[dev]" --system
      - name: Ruff lint
        run: uv pip install ruff && ruff check .
      - name: Type check (mypy)
        run: uv pip install mypy && mypy openworld_specialty_chemicals
      - name: Security scan (bandit)
        run: uv pip install bandit && bandit -q -r .
      - name: Dependency audit (pip-audit)
        run: uv pip install pip-audit && pip-audit
      - name: Run tests with coverage
        run: pytest -q --cov=openworld_specialty_chemicals --cov-report=term-missing --cov-fail-under=95
