name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies (dev + all)
        run: |
          pip install -e ".[dev,all]"

      - name: Run pre-commit (all files)
        run: |
          pip install pre-commit
          pre-commit run --all-files --show-diff-on-failure

      - name: Lint (ruff)
        run: ruff check .

      - name: Format check (ruff)
        run: ruff format --check .

      - name: Type check (mypy)
        run: mypy openworld_specialty_chemicals

      - name: Security scan (bandit)
        run: bandit -q -r .

      - name: Dependency audit (pip-audit)
        run: pip-audit

      - name: Tests with coverage
        run: pytest -q --cov=openworld_specialty_chemicals --cov-report=term-missing --cov-fail-under=85

      - name: Upload coverage report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: ./.coverage
